config/routes.rb
FirehoseApp::Application.routes.draw do

   root 'static_pages#index'
   resources :pics 

end

app/models/pic.rb
class Pic < ActiveRecord::Base
	mount_uploader :image, PicUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pics_controller.rb
class PicsController < ApplicationController

	def index
		@pics = Pic.all
	end

	def new
		@pic = Pic.new
	end

	def create
		#Pic.create(:hour => 1, 
		#			:emotion => 'Happy :)', 
		#			:learned => 'Rails, HTML and CSS!')

		#put in database
		Pic.create(pics_params)
		redirect_to pics_path
	end

	private

	def pics_params
		params.require(:pic).permit(:hour, :emotion, :learned, :image)
	end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

	def index
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pics_helper.rb
module PicsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FirehoseApp</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="navbar navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
 
      <!-- .btn-navbar is used as the toggle for collapsed navbar content -->
      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
 
      <!-- Be sure to leave the brand out there if you want it shown -->
      <%= link_to 'David Weinberger\'s App', root_path, :class => 'brand' %>
 
      <!-- Everything you want hidden at 940px or less, place within here -->
      <div class="nav-collapse collapse">
        <!-- .nav, .navbar-search, .navbar-form, etc -->

		<ul class = "nav">
			<li>
				<%= link_to 'Statuses', pics_path %>
			</li>
			<li>
				<%= link_to 'New', new_pic_path %>
			</li>
		</ul>

      </div>
 
    </div>
  </div>
</div>

<%= yield %>

</body>
</html>

app/views/pics/index.html.erb
<% @pics.each do |pic| %>
	<div class="row-fluid">
		<div class="span4 offset4 text-center steamy-hottub">

			<h1 class="custom-font">
			Hour: <%= pic.hour %> 
			<br />
			</h1>

			<%= image_tag pic.image %>

			<h2>
				<br />
				Emotion: <%= pic.emotion %> 
				<br /> <br />
				Learned: <%= pic.learned %>
				<br />
			</h2>

		</div>
	</div>
<% end %>

app/views/pics/new.html.erb
<div class="row-fluid">
	<div class="span6 offset3 text-center steamy-hottub">
		<h1 class="custom-font">
			Add your pic of web-app coding! #invoke_coffee
		</h1>	

		<br />

			<%= simple_form_for @pic do |f| %> 
				<%= f.input :hour, placeholder: '1, 2, 3, etc.', label: 'What time was this?' %> <br />
				<%= f.input :image, label: 'Photo' %> <br />
				<%= f.input :emotion, placeholder: 'Stoked, excited, confused?', label: 'How do you feel?' %> <br />
				<%= f.input :learned, placeholder: 'HTML, CSS3, Rails, Ruby, Github, etc.', label: 'What are you learning?' %> <br />
				<%= f.submit 'Save', :class => 'btn btn-warning btn-large' %>
			<% end %>
	</div>
</div>

app/views/static_pages/index.html.erb
<div class="row-fluid">

	<div class="span6 offset3 text-center steamy-hottub">


		<h1 class="custom-font">Hi, I'm David.</h1>

		<h2>I'm having a blast learning how to code web applications!</h2><br>
		

			<%= link_to 'Statuses', pics_path, :class => 'btn btn-warning btn-large' %>
			<%= link_to 'Post', new_pic_path, :class => 'btn btn-warning btn-large' %>
		
		
		<br>

	</div>
</div>


<div class="row-fluid">
	<div class="span6 offset3 text-center steamy-hottub">

		<h2>Created by David Weinberger at the RISD Firehose Weekend web development program on 2/7/14.
		</h2>		

	</div>

</div>